name: BouncyLeaves
version: '${project.version}'
main: cool.bot.bouncyleaves.BouncyLeaves
api-version: '1.20'

permissions:
  bouncyLeaves.canBounce:
    description: players without this permission will be ignored
    default: true